# Generated by Django 2.0.4 on 2018-05-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_be_like', models.CharField(blank=True, max_length=500, null=True, verbose_name='所有喜欢的用户')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '相似度推荐',
                'verbose_name_plural': '相似度推荐',
            },
        ),
    ]
