# Generated by Django 2.0.4 on 2018-05-19 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('body', models.CharField(max_length=5000, verbose_name='正文')),
                ('art_pop', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('publishTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='地点')),
                ('is_copyright', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='版权限制')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='作者')),
            ],
            options={
                'verbose_name': '游记信息',
                'verbose_name_plural': '游记信息',
            },
        ),
    ]
