# Generated by Django 2.0.4 on 2018-05-19 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Secret Superstar', max_length=50, verbose_name='名字')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('register', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
                ('is_active', models.BooleanField(choices=[(False, '未激活'), (True, '已激活')], default=False, verbose_name='是否激活')),
                ('session', models.CharField(blank=True, max_length=100, null=True, verbose_name='session')),
                ('session_time', models.IntegerField(blank=True, null=True, verbose_name='session创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
